# EnderChest Vault Plugin Configuration
# This plugin replaces Ender Chest functionality with personal vaults

# Plugin settings
plugin:
  # Enable debug messages
  debug: false

  # Use PlayerVaults integration if available
  use-playervaults: true

  # Vault number to open when using PlayerVaults (1-99)
  playervaults-number: 1

# Vault settings (only used if PlayerVaults is not available)
vault:
  # Size of personal vaults (9, 18, 27, 36, 45, or 54)
  size: 54

  # Title format for vault inventories (%player% will be replaced with player name)
  title-format: "&8Personal Vault - %player%"

# Messages
messages:
  # Message when opening vault
  vault-opened: "&6Opening your personal vault..."

  # Permission denied messages
  no-permission: "&cYou don't have permission to use this!"
  no-vault-permission: "&cYou don't have permission to use personal vaults!"

  # Command usage
  player-only: "&cThis command can only be used by players!"

  # PlayerVaults integration
  playervaults-not-found: "&cPlayerVaults plugin not found! Using built-in vault system."